### ISSUE TITLE
WebDav & Two Factor Authentication

### ISSUE THREAD

**Issue by MaxenceG2M** [rullzer/twofactor_email#69]
Hello,

I use a WebDav explorer ([Hopic Explorer](https://www.microsoft.com/en-gb/p/hopic-explorer/9nblggh4t1xh?ocid=AID2000142_aff_7809_1246483) in this case) and I don't know how two factor authentication should be handled.
Is it up to the explorer to manage it? 
Anyway. I can't connect to the Nextcloud when two-factor authentication is enabled, it's probably not up to the application to handle that, but I'm asking here in doubt.

Would there be a way to log the explorer despite this double authentication?

(By the way, thank you very much for this application which allow really simply to enable two factor authentication :) Thank to you!)

**Comment by deneb2** [comment]
same problem, I cannot login using DAVx^2

**Comment by RoelReijn** [comment]
@MaxenceG2M and @deneb2 
You might have already fixed the issue but you can use build in App Passwords. When you are in the settings page you should select Security and then scroll down. Over there you should be able to see a section "Devices & Sessions", below the currently logged in devices you can create a new one. Enter a recognizable name and press Create new app password. A password will now be generated for you, make sure you store this password in a secure location since the password allows any task to be executed.

After you've generated the app password you can enter it in the password field of your application that doesn't (yet) support Nextcloud 2FA.

**Comment by MaxenceG2M** [comment]
Hi RelReijn,

I recently discovered this method (with https://github.com/xperimental/nextcloud-exporter) but I didn't think to do this to slove this problem.

Thanks for you feedback :)
